# Generated by Django 4.1.6 on 2023-02-12 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_app', '0004_alter_movie_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='currency',
            field=models.CharField(choices=[('SOM', 'Som'), ('EU', 'Euro'), ('DOL', 'Dollar'), ('RUB', 'Rubles')], default='SOM', max_length=3),
        ),
    ]
