# Generated by Django 4.1.6 on 2023-02-12 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_app', '0005_movie_currency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='currency',
            field=models.CharField(choices=[('SOM', 'Som'), ('Euro', 'Euro'), ('Dollar', 'Dollar'), ('Rubles', 'Rubles')], default='SOM', max_length=6),
        ),
    ]
